### PR TITLE
Add Fallujah

### PR DESCRIPTION
**Pull request by Nels0**
Just an initial setup.

- Added more Littlebirds
- There are asset markers around the airfield, as it is quite large. Whether this is too confusing, I'm not sure.
- Could possibly do with the addition of quadbikes or HMMVWs to assist with travel around the base

### CODE REVIEW

**Review by scooby78 — CHANGES_REQUESTED** [review]
onLoadName = "Fallujah Framework";
Should read: onLoadName = 160th official framework;
(Just copy one of the J description.ext files and change it)
The C130J can't be used with the F18 parked where it is.  I suggest putting the jets in the hangers. 
I would't put littlebirds in hangers as it will cause major issues if a pilot hits the hanging lights.
Please replace all M113 with M1117 and remove DUKE from the M1117s and M1A2s (doesn't work correctly)
Please add all datalink options to mech battle tanks, air jets and Apaches (if any) 
Please remove air service trucks and replace them with one scripted heli (service) pad 
You can change the version to 'K' to be inline with the next release

I kinda think it is a little too spread out but lets have a look after the changes..

**Comment by Nels0** [comment]
Will do. I copied directly from the Malden framework for many of the changes requested ~~so I'll make those changes to Malden also in another branch.~~
Just saw you've made those changes already. Will only touch Fallujah.

**Comment by Nels0** [comment]
Left extra Littlebirds inside hangars, they can be towed out in the case they are really needed, and are really there as scenery.
I assume DUKE refers to hiding the DUKE antenna?
Datalink, resup, aircraft locations, M113, description.ext all fixed.

**Review by scooby78 — CHANGES_REQUESTED** [review]
If they don't have a direct purpose then it really shouldn't be in the framework.. If mission makers want to add extra they can..

I noticed there are still some DUKE antennas on some mech, the DUKE function has a global hint which is really shitty coding (I don't think some inf dude running around gives a crap about mech activating DUKE :) (Yes hiding the duke antenna turns it off)

Please move the service pad off the main taxiway, any jets/ C130 will possibly use it there by mistake.  You can use the one in the 160th scripted objects too, it builds it's own trigger area and marker.

I think the Chinooks need to be closer to the spawn area.... 

Please recheck the jet placements in the hangers as some are going to hit the sides of the entrance as they try to taxi out.  I would suggest also doubling up the jets in each hanger.  You'd be able to fit more jets closer to the spawn area that way (again they are REALLY spread out)

I'm a little concerned about putting mech under those roofed areas, ARMA isn't always happy about that on dedi servers.. #shitblowsup

If you look at the other frameworks you should notice that they aren't so spread out, I would suggest using only half the base...  Otherwise everything else looks good

**Comment by scooby78** [comment]
can you also check that Mech have this in their Vehicles..  (Magazines should be the right sizes but they may not have the right contents)

SOR_M1A2_TUSKII to have:
M829A3 X20
M830A1 X10
M1028  X6

SOR_M1A2 to have:
M829A3 X20
M830A1 X10
M1069  X6

**Comment by scooby78** [comment]
Hold off on this one... The frames are way too bad with large numbers in town..  This map is not going to work.. based on performance

**Comment by AmTheAgent** [comment]
It would be my advice to leave out Fallujah - it has NEVER been a good map for performance. It's great for smaller operations but that's about it.

**Comment by Nels0** [comment]
Framework Cancelled

**Pull request closed without merging**
