### PR TITLE
Version K Malden

### PR DESCRIPTION
**Pull request by Nels0**
See https://github.com/scooby78/160th-Frameworks/pull/17

Everything moved over to the mainland.
Have tried to take advantage of the existing layout and structure without being too spread out.

Potential issues:
 - May be hard to find mechanised vehicles. Could add map markers for mechanised and armoured locations

Potential improvements:
 - Move medivac into a permanent building
 - More scenery, i.e desks, briefing area, blacksmith detritus.

### CODE REVIEW

**Comment by Nels0** [comment]
Not quite a Malden update, but wanted to propose removing dynasound and dragonfyre from PBO whitelist in this branch too - mislabeled now >:(

**Review by scooby78 — CHANGES_REQUESTED** [review]
Looks nice but too spread out.. I just not "default" mission practical. 
The jets could go where the helis are and move the helis closer to the apron..  Inf will have quite a trek to get into air transports in it's current state

**Comment by scooby78** [comment]
Potential issues:

May be hard to find mechanised vehicles. Could add map markers for mechanised and armoured locations
**AGREED.. BUT IF YOU BRING ASSETS CLOSER YOU WON'T NEED TO CLUTTER THE MAP WITH MORE MARKERS**

Potential improvements:

Move medivac into a permanent building 
**NO.. IT NEEDS TO STAY FAMILIAR THROUGHOUT ALL FRAMEWORKS**

More scenery, i.e desks, briefing area, blacksmith detritus.
**NO.. THIS ONLY TAKES AWAY FROM THE MISSION MAKERS OBJECT QUOTAS.. IT WILL ULTIMATELY EFFECT FRAMES**

**Comment by Nels0** [comment]
will make the changes.

**Review by scooby78 — APPROVED** [review]

**Pull request merged**
